export {
  GASLESS_REGISTRY_ADDRESS,
  NATIVE_TOKEN_ADDRESS,
  NOMINATION_POOLS_PRECOMPILE_ADDRESS,
  SESSION_PRECOMPILE_ADDRESS,
  STAKING_PRECOMPILE_ADDRESS,
  SUDO_ADDRESS,
} from "./addresses";
export { CHAIN_CONFIG } from "./chain";
